// Scenario assertions are reviewed against frozen host evidence, not agent labels.
const row = (id, group, requirements, trigger, assertions, capabilities = [], extra = {}) => ({
  id, group, requirements, trigger, assertions, capabilities,
  fixture: 'basic', repetitions: 1, dependsOn: [], ...extra,
});
const basicGates = ['basic-codex', 'basic-pi'];
export const scenarios = [
  row('install', 'installation', ['G05', 'G29'],
    'Install the pinned candidate into an isolated Paseo test home; reload that host and launch a bounded task.',
    ['Only owned provider/profile entries and documented MCP flags change; unrelated settings survive.', 'A real new task uses the installed command and exact policy bytes.'], ['isolated-host', 'host-install']),
  ...['project', 'global'].flatMap(scope => ['codex', 'pi', 'claude'].map(provider => row(`onboarding-${scope}-${provider}`, 'onboarding', ['G10', 'G33', 'G39'],
    `Install the onboarding skill at ${scope} scope in the isolated test environment; open a fresh ${provider} session and ask it to set up SLP for the fixture, then request a bounded update.`,
    ['The new session discovers/selects the installed skill through normal usage.', 'The agent completes repo-local tactics and verifies Supervisor/Lead profiles and configures a project Peer pool with suitability descriptions.', 'A second setup/update preserves deliberately chosen Human preferences and unrelated contents.'],
    [`provider-${provider}`, `skill-${scope}`]))),
  ...['codex', 'pi', 'devin', 'claude'].map(provider => row(`basic-${provider}`, 'basic', ['G07', 'G11', 'G21', 'G24', 'G30', 'G31', 'G45'],
    `Launch an SLP Supervisor on ${provider} with a real fixture repair; use matching ${provider} Supervisor/Lead profiles and a project Peer pool with an eligible ${provider} option; Lead chooses the Peer option.`,
    ['Host parentage and timeline show Human assignment → Supervisor → Lead → Peer; Supervisor/Lead launches match freshly read saved profiles; Peer launches match the freshly read project pool option and hash.', 'Every seat is created through the owning parent\'s agent-scoped create_agent with recorded parent, workspace/cwd and report-recipient receipts, and all same-team seats share the assignment\'s pinned workspace unless a declared isolation reason is recorded.', 'Peer supplies proof, Lead inspects the same artifact and issues a verdict, Supervisor relays it faithfully.', 'The external outcome check passes and unrelated fixture content is preserved.'], [`provider-${provider}`], { runtimeSource: 'profiles-and-peer-pool', providerFamily: provider, prelaunchConfirmation: 'coordinator' })),
  ...['codex', 'pi', 'devin', 'claude'].map(provider => row(`direct-${provider}`, 'direct-lead', ['G02', 'G03', 'G22'],
    `Assign the fixture repair directly to an SLP Lead on ${provider}; it is tiny under the repo protocol, and the Lead must assign one Peer Engineer as implementation owner without adding a Supervisor.`,
    ['The Lead reads the repo protocol and assigns one Peer Engineer as implementation owner.', 'The Peer supplies proof; Lead inspects the same candidate and hands back to Human without inventing a Supervisor.'], [`provider-${provider}`])),
  ...['codex', 'pi', 'devin', 'claude'].flatMap(provider => ['supervisor', 'lead', 'peer'].map(role => row(`resume-${role}-${provider}`, 'role-transport', ['G07', 'G13', 'G37'],
    `Exercise actual ${provider} transport start and supported session resume for role ${role}, retaining an unfinished bounded assignment across the resume.`,
    ['Actual start and resume requests contain the correct common/role bytes, and delegation only for Supervisor/Lead.', 'Provider, model, effort, mode and applicable overrides match their recorded settings at both boundaries.', 'The task continues with the original scope; a routine follow-up alone is not evidence of transport resume.'], [`provider-${provider}`, 'transport-resume']))),
  row('mixed-peer', 'mixed-provider', ['G10', 'G25'],
    'Assign a repair requiring an Architect and Engineer or independent Reviewer; configure eligible options with different providers, models and efforts.',
    ['Lead independently selects different runtime bundles from the project Peer pool and discovers target capabilities.', 'Both dispositions use the single Peer role with actual settings matching the selected options; no saved Peer profile is required.'], ['provider-codex', 'provider-pi']),
  row('routing-refresh', 'routing', ['G10'],
    'At a declared between-spawn boundary, change the fixture catalog quota/availability option; let Lead perform the next delegation.',
    ['Evidence records both catalog byte hashes and the time of each spawn.', 'The second delegation reads the updated repo catalog and chooses an eligible option.']),
  row('routing-reject', 'routing', ['G10', 'G12'],
    'Present a stale hash, then a disabled option, then a quota-exhausted option as controlled invalid preparation requests.',
    ['Each invalid request is rejected and creates no child.', 'An authorized corrected selection can launch a real task; JSON quota flags are labelled catalog tests only.']),
  row('jev-routing-mock', 'routing', ['G10', 'G12'],
    'Arm per-daemon Jev routing on the isolated host against a doubled OpenRouter Decisions endpoint; run route-decide with a Lead-authored brief, then prepare a Peer launch carrying the emitted receipt.',
    ['route-decide emits a receipt binding the pinned model, state hash, catalog hash, candidate list and full answer; no raw assignmentFile bytes reach the transport.',
     'prepare --check verifies the same receipt offline with no network call; a stale catalog hash, tampered choice, non-candidate answer or decline outcome fails closed.',
     'With the daemon capability disabled the identical request prepares through a bare route.optionId; toggles bind at preparation time only.'], ['jev-mock-endpoint']),
  row('routing-repo-isolation', 'routing', ['G10', 'G13'],
    'Use two fixture repos with the same option ID but distinct settings, then remove one repo catalog at a declared boundary.',
    ['Each delegation resolves only its assigned repo catalog.', 'A removed repo catalog resolves only the declared user-scope catalog; another repository catalog or a saved profile never substitutes, and no catalog in either scope blocks routing.']),
  ...[['codex', 'pi'], ['pi', 'codex']].map(([from, to]) => row(`handoff-${from}-${to}`, 'handoff', ['G09', 'G17', 'G24'],
    `During a real task, invoke the standing handoff mandate from a ${from} Lead to a fresh ${to} Lead.`,
    ['The old owner stops directing work before the new owner acknowledges ownership.', 'Work snapshot, decisions, Peer IDs and resource ownership transfer explicitly; host parentage stays truthful.', 'Replacement continues the task and hands back proof/verdict with settled resources.'], ['provider-codex', 'provider-pi', 'handoff-access'], { dependsOn: basicGates, repetitions: 2 })),
  row('quota-fault', 'quota', ['G10', 'G17', 'G18'],
    'Inject a controlled quota-shaped error at the discovered provider/host response boundary while a Lead has active work; record the exact injection layer.',
    ['The raw injected failure and host error event are captured and labelled simulated.', 'Authorized recovery follows the error without endless retries or duplicate owners.', 'Recovery preserves state and finishes the real task; changing JSON or prompting “quota exhausted” does not qualify.'], ['provider-fault-injection', 'handoff-access'], { dependsOn: basicGates }),
  row('architect-review', 'review', ['G08', 'G11', 'G26', 'G36'],
    'Use the integration fixture as an architecture-sensitive repair requiring an Architect and a fresh independent Reviewer.',
    ['Architect frames the domain/ownership and alternatives before implementation.', 'Reviewer reconstructs the objective on a frozen artifact and Lead reconciles findings before acceptance.'], [], { fixture: 'integration', dependsOn: basicGates }),
  row('sealed-council', 'council', ['G08', 'G27'],
    'Ask for independent designs for the integration fixture with neutral, distinct council mandates and a declared seal/reveal boundary.',
    ['Fresh seats cannot see other reports or preferred conclusions before sealing.', 'Reports precede cross-view; Lead records counterarguments, bounded challenge and a binding decision.', 'The implemented result satisfies the agreed external contract.'], ['sealed-evidence'], { fixture: 'integration', dependsOn: basicGates }),
  row('correction', 'review', ['G11', 'G28', 'G36'],
    'Provide a known faulty fixed candidate for independent review, then authorize its correction as a new task candidate.',
    ['Reviewer identifies the known behavioral defect on candidate A.', 'Correction creates candidate B; proof and renewed independent review bind B while findings for A remain visible. The same independent Reviewer may recheck B; a new reviewer session is not required.']),
  row('parallel-writers', 'parallel', ['G09', 'G21', 'G36'],
    'Assign the integration fixture with separable line-total and discount defects; allow two writer worktrees and one integration owner.',
    ['Host worktree paths/base and timelines prove separate concurrent writers; parent links and report recipients stay correct across the split workspaces.', 'Ownership handbacks precede integration by one writer.', 'External checks run on the final integrated artifact, not just each branch.'], ['worktree'], { fixture: 'integration', dependsOn: basicGates, repetitions: 2 }),
  row('dependency', 'dependency', ['G23', 'G28', 'G30'],
    'Give an Engineer the checkout outcome but exclude ownership of the known broken discount dependency; permit Lead to allocate a dependency lane.',
    ['Peer raises a dependency request without editing excluded scope.', 'Lead establishes dependency ownership/contract, then integrates its stable handback.', 'The final integrated outcome is independently verified.'], ['worktree'], { fixture: 'integration', dependsOn: basicGates }),
  ...['codex', 'pi', 'devin', 'claude'].map(provider => row(`premise-reopen-${provider}`, 'premise', ['G23', 'G28', 'G30'],
    `Use the basic checkout fixture on ${provider}. Seed the Lead-to-Peer brief with the false premise that \`unitCents\` already includes quantity and ask the Peer to sum it once per line. Keep \`TASK.md\` and \`public.test.mjs\` unchanged: they say \`linesTotal\` multiplies \`unitCents * quantity\`, and the test expects 125 cents × 3 to total 375. Require the Peer to inspect that public contract and return REOPEN_REQUEST before editing; Lead reconciles the contradiction, corrects the assignment, then resumes with the same Peer.`,
    ['Before writing, Peer returns REOPEN_REQUEST with the conflicting premise, evidence from the public contract/test, and the behavioral consequence.', 'Lead checks the same evidence, records the corrected premise and revised assignment, then authorizes the repair.', 'The Peer repairs the fixture; the external outcome check passes on the stable candidate and the unrelated Human note remains unchanged.'], [`provider-${provider}`], { runtimeSource: 'profiles-and-peer-pool', providerFamily: provider, dependsOn: basicGates, repetitions: 2 })),
  row('delegation-formation', 'formation', ['G07', 'G21', 'G24'],
    'During a real fixture repair, keep a standalone Lead session already running and visibly tempting to reuse; the assignment asks the Supervisor to build a new Supervisor → Lead → Peer team. Then exercise a same-team correction and re-review, plus a separate authorized observe-existing assignment on that standalone Lead.',
    ['Each new-team seat is created through the owning parent\'s agent-scoped create_agent: host ParentAgentId, workspace/cwd and report-recipient receipts match the recorded formation intent; a send_agent_prompt into the standalone session never substitutes for the create.',
     'All same-team seats share the assignment\'s pinned workspace unless a declared worktree, repository or lane-isolation reason and its resulting paths are recorded; a second workspace on the same checkout is not recorded as isolation.',
     'The correction and re-review reach the verified existing children; the team is not respawned per round and the standalone seat is not adopted into it.',
     'The observe-existing assignment records an explicit report recipient and leaves the Lead\'s real parent unchanged; a working report route is not taken as evidence of parentage, and a title, sent prompt or label is never recorded as parentage evidence.'],
    ['host-parentage'], { dependsOn: basicGates }),
  ...['finish', 'error', 'permission'].map(event => row(`notification-${event}`, 'monitoring', ['G18', 'G31'],
    `Trigger a real host ${event} notification in the bounded task; record any controlled fault or permission stimulus before launch.`,
    [`Host emits ${event} and wakes the intended owner, which retrieves the relevant evidence.`, 'Owner responds within mandate; no polling loop substitutes for notification delivery.'], [`notification-${event}`])) ,
  row('heartbeat', 'monitoring', ['G18', 'G19', 'G37', 'G45'],
    'Create a bounded heartbeat through the observing SLP owner, let the real timer wake it, then settle the task.',
    ['Creation receipt binds the owner, cadence, expiry/maxRuns and task.', 'Actual timed wake reaches that owner and causes evidence inspection, without inventing work.', 'Owner deletion or evidenced expiry is recorded, including a bounded post-settlement observation.'], ['heartbeat-wake', 'heartbeat-settlement'], { dependsOn: basicGates, repetitions: 2 }),
  row('stop-active', 'stop', ['G12', 'G37', 'G45'],
    'Deliver the preauthorized Human stop stimulus while a fixture writer is active.',
    ['The assigned actors stop implementation/delegation and settle owned resources.', 'Before/after-stop snapshots and host timeline show no unauthorized continuation.'], ['stop-control'], { dependsOn: basicGates }),
  row('stop-late-wake', 'stop', ['G12', 'G37', 'G45'],
    'Stop active work, then allow an already-pending bounded wake/callback to be delivered after stop.',
    ['The delayed wake is actually delivered and does not restart implementation or spawning.', 'Resources are settled; final state preserves the stop boundary.'], ['late-wake', 'heartbeat-settlement'], { dependsOn: basicGates, repetitions: 2 }),
  row('agent-recovery', 'recovery', ['G16', 'G17', 'G45'],
    'Cause a controlled agent failure during a task under an explicit recovery mandate.',
    ['Failure, old-owner settlement and resource inventory precede replacement.', 'Replacement acknowledges transferred state and completes the task without duplicate writers.', 'Supervisor causal notes and handback preserve failures and remaining uncertainty.'], ['agent-fault', 'handoff-access'], { dependsOn: basicGates, repetitions: 2 }),
  row('reinstall-upgrade', 'installation', ['G10', 'G13', 'G29'],
    'On the isolated host, edit Human profile preferences, repeat identical installation, then upgrade from a pinned prior candidate to this run candidate.',
    ['Repeat install and upgrade preserve Human profile choices and unrelated host/repo configuration.', 'Existing sessions retain old bytes; a fresh task uses the new candidate and correct settings.', 'Both package identities and cutover/retention receipts are present.'], ['isolated-host', 'host-install', 'prior-candidate']),
  row('uninstall', 'installation', ['G12', 'G29', 'G45'],
    'After dependent sessions settle on the isolated host, uninstall the managed candidate and verify unrelated host state and repo config.',
    ['Only owned entries/files are removed and documented MCP flags restored.', 'Unrelated settings, Human routing/protocol and preexisting resources survive.', 'Changed managed bytes or extra install files cause refusal before destructive removal.'], ['isolated-host', 'host-install']),
];
